Umlaut: umlaut::small_vector_base::emplace_back
capacity
data
data
emplace_back
empty
max_size
operator[]
operator[]
push_back
push_back
reserve
size
small_vector_base
template<typename T , typename Alloc = std::allocator<T>> template<typename... Args> value_type& umlaut::small_vector_base< T, Alloc >::emplace_back (Args &&... args)
Constructs an element in place at the end of the vector.
Construction of value_type is done by perfect forwarding of args to the constructor of value_type.
Template Parameters
args The constructor arguments for value_type.
Returns
Reference to the constructed element.
References umlaut::small_vector_base< T, Alloc >::data().
Referenced by umlaut::small_vector_base< T, Alloc >::push_back(), and umlaut::small_vector_base< T, Alloc >::small_vector_base().